### ISSUE TITLE
We are able to monitor [Datadog]

### ISSUE THREAD

**Issue by EggDice** [Bobcats-Coding/compd#15]
# Story

As a developer, I can open a monitoring service so that I can assess our user-facing errors

## Scenarios

```gherkin
Scenario: Monitoring Production

Given a deployed application to production
When a runtime exception happens
Then I can discover it on our monitoring service

Scenario: Monitoring Staging

Given a deployed application to production
When a runtime exception happens
Then I can discover it on our monitoring service
```

### Tasks

 - [ ] #16
 - [ ] #17
 - [x] #35

**Comment by cassus** [comment]
This may help with Rigged demo dashboard that we could show at the event. We could just show some datadog dashboard
